#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_quoted_attribute_value_token1 = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_quoted_attribute_value_token2 = 14,
  sym_text = 15,
  anon_sym_LBRACE_LBRACE = 16,
  anon_sym_LBRACE_BANG_BANG = 17,
  anon_sym_AT_LBRACE_LBRACE = 18,
  anon_sym_RBRACE_RBRACE = 19,
  anon_sym_BANG_BANG_RBRACE = 20,
  sym__start_tag_name = 21,
  sym__script_start_tag_name = 22,
  sym__style_start_tag_name = 23,
  sym__end_tag_name = 24,
  sym_erroneous_end_tag_name = 25,
  sym__implicit_end_tag = 26,
  sym_raw_text = 27,
  sym_comment = 28,
  sym_raw_echo_php = 29,
  sym_fragment = 30,
  sym_doctype = 31,
  sym__node = 32,
  sym_element = 33,
  sym_script_element = 34,
  sym_style_element = 35,
  sym_start_tag = 36,
  sym_script_start_tag = 37,
  sym_style_start_tag = 38,
  sym_self_closing_tag = 39,
  sym_end_tag = 40,
  sym_erroneous_end_tag = 41,
  sym_attribute = 42,
  sym_quoted_attribute_value = 43,
  sym_echo_statement = 44,
  sym_echo_start_tag = 45,
  sym_echo_end_tag = 46,
  aux_sym_fragment_repeat1 = 47,
  aux_sym_start_tag_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_BANG_BANG] = "{!!",
  [anon_sym_AT_LBRACE_LBRACE] = "@{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_BANG_BANG_RBRACE] = "!!}",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_raw_echo_php] = "raw_echo_php",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_echo_statement] = "echo_statement",
  [sym_echo_start_tag] = "start_tag",
  [sym_echo_end_tag] = "end_tag",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_BANG_BANG] = anon_sym_LBRACE_BANG_BANG,
  [anon_sym_AT_LBRACE_LBRACE] = anon_sym_AT_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_BANG_BANG_RBRACE] = anon_sym_BANG_BANG_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_raw_echo_php] = sym_raw_echo_php,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_echo_statement] = sym_echo_statement,
  [sym_echo_start_tag] = sym_start_tag,
  [sym_echo_end_tag] = sym_end_tag,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_BANG_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_BANG_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_echo_php] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_end_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 12,
  [17] = 11,
  [18] = 18,
  [19] = 15,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 14,
  [24] = 9,
  [25] = 13,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 18,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 20,
  [34] = 21,
  [35] = 10,
  [36] = 22,
  [37] = 27,
  [38] = 26,
  [39] = 30,
  [40] = 28,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 42,
  [45] = 41,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 52,
  [53] = 53,
  [54] = 43,
  [55] = 50,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 58,
  [61] = 57,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 63,
  [67] = 65,
  [68] = 48,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 71,
  [76] = 76,
  [77] = 77,
  [78] = 56,
  [79] = 64,
  [80] = 59,
  [81] = 77,
  [82] = 82,
  [83] = 72,
  [84] = 74,
  [85] = 76,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 89,
  [94] = 94,
  [95] = 95,
  [96] = 86,
  [97] = 94,
  [98] = 90,
  [99] = 99,
  [100] = 92,
  [101] = 95,
  [102] = 91,
  [103] = 99,
  [104] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '@') ADVANCE(10);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == '{') ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == '{') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == '{') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(25);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(21)
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(40);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE_BANG_BANG);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_AT_LBRACE_LBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BANG_BANG_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 21, .external_lex_state = 2},
  [2] = {.lex_state = 21, .external_lex_state = 3},
  [3] = {.lex_state = 21, .external_lex_state = 3},
  [4] = {.lex_state = 21, .external_lex_state = 3},
  [5] = {.lex_state = 21, .external_lex_state = 3},
  [6] = {.lex_state = 21, .external_lex_state = 3},
  [7] = {.lex_state = 21, .external_lex_state = 2},
  [8] = {.lex_state = 21, .external_lex_state = 2},
  [9] = {.lex_state = 21, .external_lex_state = 2},
  [10] = {.lex_state = 21, .external_lex_state = 2},
  [11] = {.lex_state = 21, .external_lex_state = 3},
  [12] = {.lex_state = 21, .external_lex_state = 2},
  [13] = {.lex_state = 21, .external_lex_state = 3},
  [14] = {.lex_state = 21, .external_lex_state = 3},
  [15] = {.lex_state = 21, .external_lex_state = 3},
  [16] = {.lex_state = 21, .external_lex_state = 3},
  [17] = {.lex_state = 21, .external_lex_state = 2},
  [18] = {.lex_state = 21, .external_lex_state = 3},
  [19] = {.lex_state = 21, .external_lex_state = 2},
  [20] = {.lex_state = 21, .external_lex_state = 3},
  [21] = {.lex_state = 21, .external_lex_state = 3},
  [22] = {.lex_state = 21, .external_lex_state = 3},
  [23] = {.lex_state = 21, .external_lex_state = 2},
  [24] = {.lex_state = 21, .external_lex_state = 3},
  [25] = {.lex_state = 21, .external_lex_state = 2},
  [26] = {.lex_state = 21, .external_lex_state = 3},
  [27] = {.lex_state = 21, .external_lex_state = 2},
  [28] = {.lex_state = 21, .external_lex_state = 2},
  [29] = {.lex_state = 21, .external_lex_state = 2},
  [30] = {.lex_state = 21, .external_lex_state = 3},
  [31] = {.lex_state = 21, .external_lex_state = 3},
  [32] = {.lex_state = 21, .external_lex_state = 3},
  [33] = {.lex_state = 21, .external_lex_state = 2},
  [34] = {.lex_state = 21, .external_lex_state = 2},
  [35] = {.lex_state = 21, .external_lex_state = 3},
  [36] = {.lex_state = 21, .external_lex_state = 2},
  [37] = {.lex_state = 21, .external_lex_state = 3},
  [38] = {.lex_state = 21, .external_lex_state = 2},
  [39] = {.lex_state = 21, .external_lex_state = 2},
  [40] = {.lex_state = 21, .external_lex_state = 3},
  [41] = {.lex_state = 7, .external_lex_state = 4},
  [42] = {.lex_state = 7, .external_lex_state = 4},
  [43] = {.lex_state = 7, .external_lex_state = 4},
  [44] = {.lex_state = 7, .external_lex_state = 4},
  [45] = {.lex_state = 7, .external_lex_state = 4},
  [46] = {.lex_state = 7, .external_lex_state = 2},
  [47] = {.lex_state = 7, .external_lex_state = 2},
  [48] = {.lex_state = 7, .external_lex_state = 4},
  [49] = {.lex_state = 4, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 5},
  [51] = {.lex_state = 4, .external_lex_state = 2},
  [52] = {.lex_state = 7, .external_lex_state = 2},
  [53] = {.lex_state = 7, .external_lex_state = 2},
  [54] = {.lex_state = 7, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 5},
  [56] = {.lex_state = 7, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 6},
  [59] = {.lex_state = 7, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 6},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 5},
  [63] = {.lex_state = 0, .external_lex_state = 7},
  [64] = {.lex_state = 7, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 7},
  [66] = {.lex_state = 0, .external_lex_state = 7},
  [67] = {.lex_state = 0, .external_lex_state = 7},
  [68] = {.lex_state = 7, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 7},
  [70] = {.lex_state = 0, .external_lex_state = 7},
  [71] = {.lex_state = 0, .external_lex_state = 8},
  [72] = {.lex_state = 0, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 7},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 8},
  [76] = {.lex_state = 5, .external_lex_state = 2},
  [77] = {.lex_state = 6, .external_lex_state = 2},
  [78] = {.lex_state = 7, .external_lex_state = 2},
  [79] = {.lex_state = 7, .external_lex_state = 2},
  [80] = {.lex_state = 7, .external_lex_state = 2},
  [81] = {.lex_state = 6, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 7},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 5, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 9},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 20, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 0, .external_lex_state = 10},
  [100] = {.lex_state = 0, .external_lex_state = 9},
  [101] = {.lex_state = 20, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 10},
  [104] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
  ts_external_token_raw_echo_php = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_raw_echo_php] = sym_raw_echo_php,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_raw_echo_php] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_comment] = true,
    [ts_external_token_raw_echo_php] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_BANG_BANG] = ACTIONS(1),
    [anon_sym_AT_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_BANG_BANG_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_raw_echo_php] = ACTIONS(1),
  },
  [1] = {
    [sym_fragment] = STATE(87),
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(63),
    [sym_style_start_tag] = STATE(67),
    [sym_self_closing_tag] = STATE(12),
    [sym_erroneous_end_tag] = STATE(8),
    [sym_echo_statement] = STATE(8),
    [sym_echo_start_tag] = STATE(55),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE_BANG_BANG] = ACTIONS(15),
    [anon_sym_AT_LBRACE_LBRACE] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(38), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_echo_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    STATE(66), 1,
      sym_script_start_tag,
    ACTIONS(15), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [52] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(26), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_echo_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    STATE(66), 1,
      sym_script_start_tag,
    ACTIONS(15), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [104] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      sym_text,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(19), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_echo_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    STATE(66), 1,
      sym_script_start_tag,
    ACTIONS(15), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(2), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [156] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym_text,
    ACTIONS(37), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_end_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(50), 1,
      sym_echo_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    STATE(66), 1,
      sym_script_start_tag,
    ACTIONS(15), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(3), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [208] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LT_BANG,
    ACTIONS(42), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(48), 1,
      sym_text,
    ACTIONS(54), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(50), 1,
      sym_echo_start_tag,
    STATE(65), 1,
      sym_style_start_tag,
    STATE(66), 1,
      sym_script_start_tag,
    ACTIONS(51), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [257] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      anon_sym_LT_BANG,
    ACTIONS(59), 1,
      anon_sym_LT,
    ACTIONS(62), 1,
      anon_sym_LT_SLASH,
    ACTIONS(65), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_self_closing_tag,
    STATE(55), 1,
      sym_echo_start_tag,
    STATE(63), 1,
      sym_script_start_tag,
    STATE(67), 1,
      sym_style_start_tag,
    ACTIONS(51), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [306] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_self_closing_tag,
    STATE(55), 1,
      sym_echo_start_tag,
    STATE(63), 1,
      sym_script_start_tag,
    STATE(67), 1,
      sym_style_start_tag,
    ACTIONS(15), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [371] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [387] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(80), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [419] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(88), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(92), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [451] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(96), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [467] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(84), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(100), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(96), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(104), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [547] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(108), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(112), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(72), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [611] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(88), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(116), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [643] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(120), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(124), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [691] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(128), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(132), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(136), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(104), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [755] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(76), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(112), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(120), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [819] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(116), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [835] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(128), 6,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(124), 6,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_BANG_BANG,
      anon_sym_AT_LBRACE_LBRACE,
  [867] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_GT,
    ACTIONS(142), 1,
      anon_sym_SLASH_GT,
    ACTIONS(144), 1,
      sym_attribute_name,
    STATE(44), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [884] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_attribute_name,
    ACTIONS(146), 1,
      anon_sym_GT,
    ACTIONS(148), 1,
      anon_sym_SLASH_GT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [901] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_attribute_name,
    ACTIONS(150), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [916] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_attribute_name,
    ACTIONS(146), 1,
      anon_sym_GT,
    ACTIONS(155), 1,
      anon_sym_SLASH_GT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [933] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_GT,
    ACTIONS(144), 1,
      sym_attribute_name,
    ACTIONS(157), 1,
      anon_sym_SLASH_GT,
    STATE(42), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [950] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(161), 1,
      sym_attribute_name,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [964] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(163), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [978] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_EQ,
    ACTIONS(165), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [990] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_attribute_value,
    ACTIONS(171), 1,
      anon_sym_SQUOTE,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    STATE(56), 1,
      sym_quoted_attribute_value,
  [1006] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_raw_echo_php,
    STATE(40), 1,
      sym_echo_end_tag,
    ACTIONS(175), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1020] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_attribute_value,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(78), 1,
      sym_quoted_attribute_value,
  [1036] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(185), 1,
      anon_sym_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1050] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(187), 1,
      anon_sym_GT,
    STATE(47), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1064] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_GT,
    ACTIONS(189), 1,
      sym_attribute_name,
    STATE(54), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1078] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      sym_raw_echo_php,
    STATE(28), 1,
      sym_echo_end_tag,
    ACTIONS(192), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1101] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(34), 1,
      sym_echo_end_tag,
    ACTIONS(192), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1112] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym__start_tag_name,
    ACTIONS(200), 1,
      sym__script_start_tag_name,
    ACTIONS(202), 1,
      sym__style_start_tag_name,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1134] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym__script_start_tag_name,
    ACTIONS(202), 1,
      sym__style_start_tag_name,
    ACTIONS(206), 1,
      sym__start_tag_name,
  [1147] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(21), 1,
      sym_echo_end_tag,
    ACTIONS(175), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 3,
      sym_raw_echo_php,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1167] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LT_SLASH,
    ACTIONS(212), 1,
      sym_raw_text,
    STATE(23), 1,
      sym_end_tag,
  [1180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1189] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LT_SLASH,
    ACTIONS(218), 1,
      sym_raw_text,
    STATE(13), 1,
      sym_end_tag,
  [1202] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LT_SLASH,
    ACTIONS(220), 1,
      sym_raw_text,
    STATE(14), 1,
      sym_end_tag,
  [1215] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LT_SLASH,
    ACTIONS(222), 1,
      sym_raw_text,
    STATE(25), 1,
      sym_end_tag,
  [1228] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_EQ,
    ACTIONS(165), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1239] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1255] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym__end_tag_name,
    ACTIONS(232), 1,
      sym_erroneous_end_tag_name,
  [1265] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LT_SLASH,
    STATE(36), 1,
      sym_end_tag,
  [1275] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LT_SLASH,
    STATE(9), 1,
      sym_end_tag,
  [1293] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(236), 1,
      sym__end_tag_name,
  [1303] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    ACTIONS(240), 1,
      aux_sym_quoted_attribute_value_token2,
  [1313] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_SQUOTE,
    ACTIONS(242), 1,
      aux_sym_quoted_attribute_value_token1,
  [1323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1331] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1339] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_SQUOTE,
    ACTIONS(246), 1,
      aux_sym_quoted_attribute_value_token1,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LT_SLASH,
    STATE(22), 1,
      sym_end_tag,
  [1375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LT_SLASH,
    STATE(24), 1,
      sym_end_tag,
  [1385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    ACTIONS(250), 1,
      aux_sym_quoted_attribute_value_token2,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_GT,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
  [1409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym__doctype,
  [1416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_GT,
  [1423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_DQUOTE,
  [1430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_GT,
  [1437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
  [1444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_GT,
  [1451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_SQUOTE,
  [1458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      aux_sym_doctype_token1,
  [1465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_GT,
  [1472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_SQUOTE,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym__end_tag_name,
  [1493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_erroneous_end_tag_name,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      aux_sym_doctype_token1,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_GT,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym__end_tag_name,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 104,
  [SMALL_STATE(5)] = 156,
  [SMALL_STATE(6)] = 208,
  [SMALL_STATE(7)] = 257,
  [SMALL_STATE(8)] = 306,
  [SMALL_STATE(9)] = 355,
  [SMALL_STATE(10)] = 371,
  [SMALL_STATE(11)] = 387,
  [SMALL_STATE(12)] = 403,
  [SMALL_STATE(13)] = 419,
  [SMALL_STATE(14)] = 435,
  [SMALL_STATE(15)] = 451,
  [SMALL_STATE(16)] = 467,
  [SMALL_STATE(17)] = 483,
  [SMALL_STATE(18)] = 499,
  [SMALL_STATE(19)] = 515,
  [SMALL_STATE(20)] = 531,
  [SMALL_STATE(21)] = 547,
  [SMALL_STATE(22)] = 563,
  [SMALL_STATE(23)] = 579,
  [SMALL_STATE(24)] = 595,
  [SMALL_STATE(25)] = 611,
  [SMALL_STATE(26)] = 627,
  [SMALL_STATE(27)] = 643,
  [SMALL_STATE(28)] = 659,
  [SMALL_STATE(29)] = 675,
  [SMALL_STATE(30)] = 691,
  [SMALL_STATE(31)] = 707,
  [SMALL_STATE(32)] = 723,
  [SMALL_STATE(33)] = 739,
  [SMALL_STATE(34)] = 755,
  [SMALL_STATE(35)] = 771,
  [SMALL_STATE(36)] = 787,
  [SMALL_STATE(37)] = 803,
  [SMALL_STATE(38)] = 819,
  [SMALL_STATE(39)] = 835,
  [SMALL_STATE(40)] = 851,
  [SMALL_STATE(41)] = 867,
  [SMALL_STATE(42)] = 884,
  [SMALL_STATE(43)] = 901,
  [SMALL_STATE(44)] = 916,
  [SMALL_STATE(45)] = 933,
  [SMALL_STATE(46)] = 950,
  [SMALL_STATE(47)] = 964,
  [SMALL_STATE(48)] = 978,
  [SMALL_STATE(49)] = 990,
  [SMALL_STATE(50)] = 1006,
  [SMALL_STATE(51)] = 1020,
  [SMALL_STATE(52)] = 1036,
  [SMALL_STATE(53)] = 1050,
  [SMALL_STATE(54)] = 1064,
  [SMALL_STATE(55)] = 1078,
  [SMALL_STATE(56)] = 1092,
  [SMALL_STATE(57)] = 1101,
  [SMALL_STATE(58)] = 1112,
  [SMALL_STATE(59)] = 1125,
  [SMALL_STATE(60)] = 1134,
  [SMALL_STATE(61)] = 1147,
  [SMALL_STATE(62)] = 1158,
  [SMALL_STATE(63)] = 1167,
  [SMALL_STATE(64)] = 1180,
  [SMALL_STATE(65)] = 1189,
  [SMALL_STATE(66)] = 1202,
  [SMALL_STATE(67)] = 1215,
  [SMALL_STATE(68)] = 1228,
  [SMALL_STATE(69)] = 1239,
  [SMALL_STATE(70)] = 1247,
  [SMALL_STATE(71)] = 1255,
  [SMALL_STATE(72)] = 1265,
  [SMALL_STATE(73)] = 1275,
  [SMALL_STATE(74)] = 1283,
  [SMALL_STATE(75)] = 1293,
  [SMALL_STATE(76)] = 1303,
  [SMALL_STATE(77)] = 1313,
  [SMALL_STATE(78)] = 1323,
  [SMALL_STATE(79)] = 1331,
  [SMALL_STATE(80)] = 1339,
  [SMALL_STATE(81)] = 1347,
  [SMALL_STATE(82)] = 1357,
  [SMALL_STATE(83)] = 1365,
  [SMALL_STATE(84)] = 1375,
  [SMALL_STATE(85)] = 1385,
  [SMALL_STATE(86)] = 1395,
  [SMALL_STATE(87)] = 1402,
  [SMALL_STATE(88)] = 1409,
  [SMALL_STATE(89)] = 1416,
  [SMALL_STATE(90)] = 1423,
  [SMALL_STATE(91)] = 1430,
  [SMALL_STATE(92)] = 1437,
  [SMALL_STATE(93)] = 1444,
  [SMALL_STATE(94)] = 1451,
  [SMALL_STATE(95)] = 1458,
  [SMALL_STATE(96)] = 1465,
  [SMALL_STATE(97)] = 1472,
  [SMALL_STATE(98)] = 1479,
  [SMALL_STATE(99)] = 1486,
  [SMALL_STATE(100)] = 1493,
  [SMALL_STATE(101)] = 1500,
  [SMALL_STATE(102)] = 1507,
  [SMALL_STATE(103)] = 1514,
  [SMALL_STATE(104)] = 1521,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(104),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(58),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(100),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(6),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(62),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(88),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(60),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(92),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_end_tag, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_end_tag, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(48),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(68),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_start_tag, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [254] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_blade_external_scanner_create(void);
void tree_sitter_blade_external_scanner_destroy(void *);
bool tree_sitter_blade_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_blade_external_scanner_serialize(void *, char *);
void tree_sitter_blade_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_blade(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_blade_external_scanner_create,
      tree_sitter_blade_external_scanner_destroy,
      tree_sitter_blade_external_scanner_scan,
      tree_sitter_blade_external_scanner_serialize,
      tree_sitter_blade_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
