#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_quoted_attribute_value_token1 = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_quoted_attribute_value_token2 = 14,
  sym_text = 15,
  aux_sym_echo_statement_token1 = 16,
  sym_echo_start_tag = 17,
  anon_sym_RBRACE_RBRACE = 18,
  anon_sym_BANG_BANG_RBRACE = 19,
  sym__start_tag_name = 20,
  sym__script_start_tag_name = 21,
  sym__style_start_tag_name = 22,
  sym__end_tag_name = 23,
  sym_erroneous_end_tag_name = 24,
  sym__implicit_end_tag = 25,
  sym_raw_text = 26,
  sym_comment = 27,
  sym_fragment = 28,
  sym_doctype = 29,
  sym__node = 30,
  sym_element = 31,
  sym_script_element = 32,
  sym_style_element = 33,
  sym_start_tag = 34,
  sym_script_start_tag = 35,
  sym_style_start_tag = 36,
  sym_self_closing_tag = 37,
  sym_end_tag = 38,
  sym_erroneous_end_tag = 39,
  sym_attribute = 40,
  sym_quoted_attribute_value = 41,
  sym_echo_statement = 42,
  sym_echo_end_tag = 43,
  aux_sym_fragment_repeat1 = 44,
  aux_sym_start_tag_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [aux_sym_echo_statement_token1] = "echo_statement_token1",
  [sym_echo_start_tag] = "start_tag",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_BANG_BANG_RBRACE] = "!!}",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_echo_statement] = "echo_statement",
  [sym_echo_end_tag] = "end_tag",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [aux_sym_echo_statement_token1] = aux_sym_echo_statement_token1,
  [sym_echo_start_tag] = sym_start_tag,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_BANG_BANG_RBRACE] = anon_sym_BANG_BANG_RBRACE,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_echo_statement] = sym_echo_statement,
  [sym_echo_end_tag] = sym_end_tag,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_echo_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_echo_start_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_BANG_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_end_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 22,
  [26] = 14,
  [27] = 20,
  [28] = 21,
  [29] = 19,
  [30] = 13,
  [31] = 31,
  [32] = 18,
  [33] = 9,
  [34] = 34,
  [35] = 35,
  [36] = 34,
  [37] = 35,
  [38] = 10,
  [39] = 17,
  [40] = 40,
  [41] = 16,
  [42] = 11,
  [43] = 12,
  [44] = 15,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 45,
  [50] = 46,
  [51] = 51,
  [52] = 47,
  [53] = 48,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 56,
  [60] = 60,
  [61] = 51,
  [62] = 55,
  [63] = 63,
  [64] = 64,
  [65] = 54,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 67,
  [71] = 64,
  [72] = 72,
  [73] = 69,
  [74] = 74,
  [75] = 75,
  [76] = 68,
  [77] = 77,
  [78] = 66,
  [79] = 75,
  [80] = 80,
  [81] = 81,
  [82] = 81,
  [83] = 83,
  [84] = 84,
  [85] = 83,
  [86] = 80,
  [87] = 77,
  [88] = 88,
  [89] = 72,
  [90] = 74,
  [91] = 91,
  [92] = 92,
  [93] = 84,
  [94] = 94,
  [95] = 95,
  [96] = 92,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 97,
  [103] = 103,
  [104] = 100,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 106,
  [109] = 109,
  [110] = 109,
  [111] = 101,
  [112] = 107,
  [113] = 98,
  [114] = 99,
  [115] = 105,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '@') ADVANCE(9);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == '{') ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '{') ADVANCE(2);
      END_STATE();
    case 10:
      if (lookahead == '{') ADVANCE(48);
      END_STATE();
    case 11:
      if (lookahead == '{') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 21:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(24);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(41);
      if (lookahead == '{') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '@') ADVANCE(45);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_echo_statement_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_echo_start_tag);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BANG_BANG_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 22, .external_lex_state = 2},
  [2] = {.lex_state = 22, .external_lex_state = 3},
  [3] = {.lex_state = 22, .external_lex_state = 3},
  [4] = {.lex_state = 22, .external_lex_state = 3},
  [5] = {.lex_state = 22, .external_lex_state = 3},
  [6] = {.lex_state = 22, .external_lex_state = 2},
  [7] = {.lex_state = 22, .external_lex_state = 3},
  [8] = {.lex_state = 22, .external_lex_state = 2},
  [9] = {.lex_state = 22, .external_lex_state = 3},
  [10] = {.lex_state = 22, .external_lex_state = 3},
  [11] = {.lex_state = 22, .external_lex_state = 3},
  [12] = {.lex_state = 22, .external_lex_state = 3},
  [13] = {.lex_state = 22, .external_lex_state = 2},
  [14] = {.lex_state = 22, .external_lex_state = 3},
  [15] = {.lex_state = 22, .external_lex_state = 3},
  [16] = {.lex_state = 22, .external_lex_state = 3},
  [17] = {.lex_state = 22, .external_lex_state = 3},
  [18] = {.lex_state = 22, .external_lex_state = 3},
  [19] = {.lex_state = 22, .external_lex_state = 3},
  [20] = {.lex_state = 22, .external_lex_state = 3},
  [21] = {.lex_state = 22, .external_lex_state = 2},
  [22] = {.lex_state = 22, .external_lex_state = 2},
  [23] = {.lex_state = 22, .external_lex_state = 2},
  [24] = {.lex_state = 22, .external_lex_state = 3},
  [25] = {.lex_state = 22, .external_lex_state = 3},
  [26] = {.lex_state = 22, .external_lex_state = 2},
  [27] = {.lex_state = 22, .external_lex_state = 2},
  [28] = {.lex_state = 22, .external_lex_state = 3},
  [29] = {.lex_state = 22, .external_lex_state = 2},
  [30] = {.lex_state = 22, .external_lex_state = 3},
  [31] = {.lex_state = 22, .external_lex_state = 3},
  [32] = {.lex_state = 22, .external_lex_state = 2},
  [33] = {.lex_state = 22, .external_lex_state = 2},
  [34] = {.lex_state = 22, .external_lex_state = 3},
  [35] = {.lex_state = 22, .external_lex_state = 2},
  [36] = {.lex_state = 22, .external_lex_state = 2},
  [37] = {.lex_state = 22, .external_lex_state = 3},
  [38] = {.lex_state = 22, .external_lex_state = 2},
  [39] = {.lex_state = 22, .external_lex_state = 2},
  [40] = {.lex_state = 22, .external_lex_state = 3},
  [41] = {.lex_state = 22, .external_lex_state = 2},
  [42] = {.lex_state = 22, .external_lex_state = 2},
  [43] = {.lex_state = 22, .external_lex_state = 2},
  [44] = {.lex_state = 22, .external_lex_state = 2},
  [45] = {.lex_state = 47, .external_lex_state = 4},
  [46] = {.lex_state = 7, .external_lex_state = 5},
  [47] = {.lex_state = 47, .external_lex_state = 4},
  [48] = {.lex_state = 7, .external_lex_state = 5},
  [49] = {.lex_state = 47, .external_lex_state = 4},
  [50] = {.lex_state = 7, .external_lex_state = 5},
  [51] = {.lex_state = 7, .external_lex_state = 5},
  [52] = {.lex_state = 47, .external_lex_state = 4},
  [53] = {.lex_state = 7, .external_lex_state = 5},
  [54] = {.lex_state = 4, .external_lex_state = 2},
  [55] = {.lex_state = 47, .external_lex_state = 6},
  [56] = {.lex_state = 47, .external_lex_state = 6},
  [57] = {.lex_state = 7, .external_lex_state = 2},
  [58] = {.lex_state = 7, .external_lex_state = 2},
  [59] = {.lex_state = 47, .external_lex_state = 6},
  [60] = {.lex_state = 7, .external_lex_state = 2},
  [61] = {.lex_state = 7, .external_lex_state = 2},
  [62] = {.lex_state = 47, .external_lex_state = 6},
  [63] = {.lex_state = 7, .external_lex_state = 2},
  [64] = {.lex_state = 7, .external_lex_state = 5},
  [65] = {.lex_state = 4, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 7},
  [67] = {.lex_state = 0, .external_lex_state = 8},
  [68] = {.lex_state = 0, .external_lex_state = 6},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 8},
  [71] = {.lex_state = 7, .external_lex_state = 2},
  [72] = {.lex_state = 7, .external_lex_state = 5},
  [73] = {.lex_state = 0, .external_lex_state = 6},
  [74] = {.lex_state = 7, .external_lex_state = 5},
  [75] = {.lex_state = 0, .external_lex_state = 8},
  [76] = {.lex_state = 0, .external_lex_state = 6},
  [77] = {.lex_state = 7, .external_lex_state = 5},
  [78] = {.lex_state = 0, .external_lex_state = 7},
  [79] = {.lex_state = 0, .external_lex_state = 8},
  [80] = {.lex_state = 6, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 9},
  [82] = {.lex_state = 0, .external_lex_state = 9},
  [83] = {.lex_state = 5, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 5, .external_lex_state = 2},
  [86] = {.lex_state = 6, .external_lex_state = 2},
  [87] = {.lex_state = 7, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 8},
  [89] = {.lex_state = 7, .external_lex_state = 2},
  [90] = {.lex_state = 7, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 8},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 0, .external_lex_state = 10},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 11},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 21, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 11},
  [112] = {.lex_state = 21, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 10},
  [115] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
  ts_external_token_RBRACE_RBRACE = 9,
  ts_external_token_BANG_BANG_RBRACE = 10,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [ts_external_token_BANG_BANG_RBRACE] = anon_sym_BANG_BANG_RBRACE,
};

static const bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_RBRACE_RBRACE] = true,
    [ts_external_token_BANG_BANG_RBRACE] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_RBRACE_RBRACE] = true,
    [ts_external_token_BANG_BANG_RBRACE] = true,
  },
  [5] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_comment] = true,
    [ts_external_token_RBRACE_RBRACE] = true,
    [ts_external_token_BANG_BANG_RBRACE] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [11] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_echo_start_tag] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_BANG_BANG_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(103),
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(70),
    [sym_style_start_tag] = STATE(79),
    [sym_self_closing_tag] = STATE(13),
    [sym_erroneous_end_tag] = STATE(8),
    [sym_echo_statement] = STATE(8),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym_echo_start_tag] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      sym_echo_start_tag,
    ACTIONS(27), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(15), 1,
      sym_end_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [47] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(25), 1,
      sym_echo_start_tag,
    ACTIONS(29), 1,
      sym_text,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_end_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(2), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [94] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      sym_echo_start_tag,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(44), 1,
      sym_end_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [141] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      sym_echo_start_tag,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym_text,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(23), 1,
      sym_end_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(4), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [188] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_LT_BANG,
    ACTIONS(46), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LT_SLASH,
    ACTIONS(52), 1,
      sym_text,
    ACTIONS(55), 1,
      sym_echo_start_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(13), 1,
      sym_self_closing_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(79), 1,
      sym_style_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [232] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym__implicit_end_tag,
    ACTIONS(58), 1,
      anon_sym_LT_BANG,
    ACTIONS(61), 1,
      anon_sym_LT,
    ACTIONS(64), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_text,
    ACTIONS(70), 1,
      sym_echo_start_tag,
    STATE(3), 1,
      sym_start_tag,
    STATE(30), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [276] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym_echo_start_tag,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(13), 1,
      sym_self_closing_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(79), 1,
      sym_style_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_echo_statement,
      aux_sym_fragment_repeat1,
  [320] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(77), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(81), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(85), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(89), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [376] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(93), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(97), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(101), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(105), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [432] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(109), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [446] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(113), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [460] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(117), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(121), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [488] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [502] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [516] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(133), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(133), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(129), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [558] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(97), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [572] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [586] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(125), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [600] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [614] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(93), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [628] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(137), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(113), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [656] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [670] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(141), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [684] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(145), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [726] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [740] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [754] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(149), 4,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [782] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [796] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(89), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [810] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_echo_start_tag,
  [824] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      aux_sym_echo_statement_token1,
    ACTIONS(157), 1,
      sym_raw_text,
    STATE(16), 1,
      sym_echo_end_tag,
    ACTIONS(155), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [841] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(161), 1,
      anon_sym_SLASH_GT,
    ACTIONS(163), 1,
      sym_attribute_name,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [858] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      aux_sym_echo_statement_token1,
    ACTIONS(167), 1,
      sym_raw_text,
    STATE(25), 1,
      sym_echo_end_tag,
    ACTIONS(155), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [875] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_attribute_name,
    ACTIONS(169), 1,
      anon_sym_GT,
    ACTIONS(171), 1,
      anon_sym_SLASH_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [892] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      aux_sym_echo_statement_token1,
    ACTIONS(177), 1,
      sym_raw_text,
    STATE(41), 1,
      sym_echo_end_tag,
    ACTIONS(175), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [909] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(163), 1,
      sym_attribute_name,
    ACTIONS(179), 1,
      anon_sym_SLASH_GT,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [926] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_attribute_name,
    ACTIONS(181), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [941] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_echo_statement_token1,
    ACTIONS(188), 1,
      sym_raw_text,
    STATE(22), 1,
      sym_echo_end_tag,
    ACTIONS(175), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [958] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_attribute_name,
    ACTIONS(169), 1,
      anon_sym_GT,
    ACTIONS(190), 1,
      anon_sym_SLASH_GT,
    STATE(50), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [975] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_attribute_value,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_quoted_attribute_value,
  [991] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      aux_sym_echo_statement_token1,
    STATE(16), 1,
      sym_echo_end_tag,
    ACTIONS(155), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1005] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      aux_sym_echo_statement_token1,
    STATE(36), 1,
      sym_echo_end_tag,
    ACTIONS(175), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1019] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_GT,
    ACTIONS(202), 1,
      sym_attribute_name,
    STATE(61), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_attribute_name,
    ACTIONS(204), 1,
      anon_sym_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1047] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      aux_sym_echo_statement_token1,
    STATE(34), 1,
      sym_echo_end_tag,
    ACTIONS(155), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1061] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_attribute_name,
    ACTIONS(208), 1,
      anon_sym_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1075] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_GT,
    ACTIONS(210), 1,
      sym_attribute_name,
    STATE(61), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1089] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      aux_sym_echo_statement_token1,
    STATE(41), 1,
      sym_echo_end_tag,
    ACTIONS(175), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1103] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_attribute_name,
    ACTIONS(213), 1,
      anon_sym_GT,
    STATE(61), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1117] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_EQ,
    ACTIONS(215), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1129] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_attribute_value,
    ACTIONS(221), 1,
      anon_sym_SQUOTE,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      sym_quoted_attribute_value,
  [1145] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym__start_tag_name,
    ACTIONS(227), 1,
      sym__script_start_tag_name,
    ACTIONS(229), 1,
      sym__style_start_tag_name,
  [1158] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    ACTIONS(233), 1,
      sym_raw_text,
    STATE(20), 1,
      sym_end_tag,
  [1171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(33), 1,
      sym_echo_end_tag,
    ACTIONS(235), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(36), 1,
      sym_echo_end_tag,
    ACTIONS(235), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1193] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LT_SLASH,
    ACTIONS(239), 1,
      sym_raw_text,
    STATE(27), 1,
      sym_end_tag,
  [1206] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_EQ,
    ACTIONS(215), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1226] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(34), 1,
      sym_echo_end_tag,
    ACTIONS(245), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1246] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 1,
      sym_raw_text,
    STATE(19), 1,
      sym_end_tag,
  [1259] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(9), 1,
      sym_echo_end_tag,
    ACTIONS(245), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_BANG_BANG_RBRACE,
  [1270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1279] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym__script_start_tag_name,
    ACTIONS(229), 1,
      sym__style_start_tag_name,
    ACTIONS(253), 1,
      sym__start_tag_name,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LT_SLASH,
    ACTIONS(255), 1,
      sym_raw_text,
    STATE(29), 1,
      sym_end_tag,
  [1305] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_SQUOTE,
    ACTIONS(259), 1,
      aux_sym_quoted_attribute_value_token1,
  [1315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym__end_tag_name,
    ACTIONS(263), 1,
      sym_erroneous_end_tag_name,
  [1325] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(265), 1,
      sym__end_tag_name,
  [1335] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_DQUOTE,
    ACTIONS(267), 1,
      aux_sym_quoted_attribute_value_token2,
  [1345] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LT_SLASH,
    STATE(26), 1,
      sym_end_tag,
  [1355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
    ACTIONS(271), 1,
      aux_sym_quoted_attribute_value_token2,
  [1365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_SQUOTE,
    ACTIONS(273), 1,
      aux_sym_quoted_attribute_value_token1,
  [1375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    STATE(12), 1,
      sym_end_tag,
  [1425] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    STATE(14), 1,
      sym_end_tag,
  [1435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1443] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1451] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LT_SLASH,
    STATE(43), 1,
      sym_end_tag,
  [1461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_GT,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_GT,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym__end_tag_name,
  [1482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_GT,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_erroneous_end_tag_name,
  [1496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_GT,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      ts_builtin_sym_end,
  [1510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_GT,
  [1517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym__doctype,
  [1524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_SQUOTE,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      aux_sym_doctype_token1,
  [1538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_SQUOTE,
  [1545] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_DQUOTE,
  [1552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_DQUOTE,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_erroneous_end_tag_name,
  [1566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      aux_sym_doctype_token1,
  [1573] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_GT,
  [1580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym__end_tag_name,
  [1587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 232,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 334,
  [SMALL_STATE(11)] = 348,
  [SMALL_STATE(12)] = 362,
  [SMALL_STATE(13)] = 376,
  [SMALL_STATE(14)] = 390,
  [SMALL_STATE(15)] = 404,
  [SMALL_STATE(16)] = 418,
  [SMALL_STATE(17)] = 432,
  [SMALL_STATE(18)] = 446,
  [SMALL_STATE(19)] = 460,
  [SMALL_STATE(20)] = 474,
  [SMALL_STATE(21)] = 488,
  [SMALL_STATE(22)] = 502,
  [SMALL_STATE(23)] = 516,
  [SMALL_STATE(24)] = 530,
  [SMALL_STATE(25)] = 544,
  [SMALL_STATE(26)] = 558,
  [SMALL_STATE(27)] = 572,
  [SMALL_STATE(28)] = 586,
  [SMALL_STATE(29)] = 600,
  [SMALL_STATE(30)] = 614,
  [SMALL_STATE(31)] = 628,
  [SMALL_STATE(32)] = 642,
  [SMALL_STATE(33)] = 656,
  [SMALL_STATE(34)] = 670,
  [SMALL_STATE(35)] = 684,
  [SMALL_STATE(36)] = 698,
  [SMALL_STATE(37)] = 712,
  [SMALL_STATE(38)] = 726,
  [SMALL_STATE(39)] = 740,
  [SMALL_STATE(40)] = 754,
  [SMALL_STATE(41)] = 768,
  [SMALL_STATE(42)] = 782,
  [SMALL_STATE(43)] = 796,
  [SMALL_STATE(44)] = 810,
  [SMALL_STATE(45)] = 824,
  [SMALL_STATE(46)] = 841,
  [SMALL_STATE(47)] = 858,
  [SMALL_STATE(48)] = 875,
  [SMALL_STATE(49)] = 892,
  [SMALL_STATE(50)] = 909,
  [SMALL_STATE(51)] = 926,
  [SMALL_STATE(52)] = 941,
  [SMALL_STATE(53)] = 958,
  [SMALL_STATE(54)] = 975,
  [SMALL_STATE(55)] = 991,
  [SMALL_STATE(56)] = 1005,
  [SMALL_STATE(57)] = 1019,
  [SMALL_STATE(58)] = 1033,
  [SMALL_STATE(59)] = 1047,
  [SMALL_STATE(60)] = 1061,
  [SMALL_STATE(61)] = 1075,
  [SMALL_STATE(62)] = 1089,
  [SMALL_STATE(63)] = 1103,
  [SMALL_STATE(64)] = 1117,
  [SMALL_STATE(65)] = 1129,
  [SMALL_STATE(66)] = 1145,
  [SMALL_STATE(67)] = 1158,
  [SMALL_STATE(68)] = 1171,
  [SMALL_STATE(69)] = 1182,
  [SMALL_STATE(70)] = 1193,
  [SMALL_STATE(71)] = 1206,
  [SMALL_STATE(72)] = 1217,
  [SMALL_STATE(73)] = 1226,
  [SMALL_STATE(74)] = 1237,
  [SMALL_STATE(75)] = 1246,
  [SMALL_STATE(76)] = 1259,
  [SMALL_STATE(77)] = 1270,
  [SMALL_STATE(78)] = 1279,
  [SMALL_STATE(79)] = 1292,
  [SMALL_STATE(80)] = 1305,
  [SMALL_STATE(81)] = 1315,
  [SMALL_STATE(82)] = 1325,
  [SMALL_STATE(83)] = 1335,
  [SMALL_STATE(84)] = 1345,
  [SMALL_STATE(85)] = 1355,
  [SMALL_STATE(86)] = 1365,
  [SMALL_STATE(87)] = 1375,
  [SMALL_STATE(88)] = 1383,
  [SMALL_STATE(89)] = 1391,
  [SMALL_STATE(90)] = 1399,
  [SMALL_STATE(91)] = 1407,
  [SMALL_STATE(92)] = 1415,
  [SMALL_STATE(93)] = 1425,
  [SMALL_STATE(94)] = 1435,
  [SMALL_STATE(95)] = 1443,
  [SMALL_STATE(96)] = 1451,
  [SMALL_STATE(97)] = 1461,
  [SMALL_STATE(98)] = 1468,
  [SMALL_STATE(99)] = 1475,
  [SMALL_STATE(100)] = 1482,
  [SMALL_STATE(101)] = 1489,
  [SMALL_STATE(102)] = 1496,
  [SMALL_STATE(103)] = 1503,
  [SMALL_STATE(104)] = 1510,
  [SMALL_STATE(105)] = 1517,
  [SMALL_STATE(106)] = 1524,
  [SMALL_STATE(107)] = 1531,
  [SMALL_STATE(108)] = 1538,
  [SMALL_STATE(109)] = 1545,
  [SMALL_STATE(110)] = 1552,
  [SMALL_STATE(111)] = 1559,
  [SMALL_STATE(112)] = 1566,
  [SMALL_STATE(113)] = 1573,
  [SMALL_STATE(114)] = 1580,
  [SMALL_STATE(115)] = 1587,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(105),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(66),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(101),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(6),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(52),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(115),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(78),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(111),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(47),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 5),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_end_tag, 1),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_end_tag, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(64),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(71),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [293] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_blade_external_scanner_create(void);
void tree_sitter_blade_external_scanner_destroy(void *);
bool tree_sitter_blade_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_blade_external_scanner_serialize(void *, char *);
void tree_sitter_blade_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_blade(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_blade_external_scanner_create,
      tree_sitter_blade_external_scanner_destroy,
      tree_sitter_blade_external_scanner_scan,
      tree_sitter_blade_external_scanner_serialize,
      tree_sitter_blade_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
